### ISSUE TITLE
Fix indentations

### ISSUE THREAD

**Issue by Bravo555** [MaksemiL/STRONA1BOGITHUBCHCETAK#2]
Well, these indents are a little messy. Try to fix them before doing more things with your website (the later you do this, the more work you have).

I recommend you these settings:
- indentation type: tabs ("indentation type: hard" in Atom)
- indentation size: 4

After that, you can fix it manually (if you have some time to spend) or use [atom-beautify](https://atom.io/packages/atom-beautify) package.

One more thing: I recommend you to use [editorconfig](http://editorconfig.org/) to have your editor settings under control ([atom package](https://atom.io/packages/editorconfig)).

(When you will be fixing this, you can close this issue by commit message and you won't have to go here and close it manually. It also nicely pairs the issue and the fix.)

**Comment by MaksemiL** [comment]
Ok thx close
