### ISSUE TITLE
Escape & character

### ISSUE THREAD

**Issue by Bravo555** [MaksemiL/STRONA1BOGITHUBCHCETAK#3]
You have unescaped character [here](https://github.com/MaksemiL/STRONA1BOGITHUBCHCETAK/blob/56c6fa43b270b5fb58a0b4ccc3be9e9a06242342/index.html#L60) and as you can see, github highlights it. Use html entities to escape this character properly.

(When you will be fixing this, you can [close this issue by commit message](https://help.github.com/articles/closing-issues-via-commit-messages/) and you won't have to go here and close it manually. It also nicely pairs the issue and the fix.)

**Comment by MaksemiL** [comment]
Ok i done it thanks 👍

**Comment by Bravo555** [comment]
But where's the fix? Commit it.

**Comment by Bravo555** [comment]
Yes, I can see. But next time I recommend you to include `fixes/resolves/closes/etc. #[issue number]` to close issue automatically via commit.
